feat: add two services
bad-decision/java-explore-with-me pull request #2
Opened 2023-01-08 20:36 UTC by bad-decision

2023-01-09 19:46 UTC, sergeymamonov requested changes

2023-01-09 19:46 UTC, sergeymamonov commented on main-service/src/main/resources/schema.sql
> +--     views BIGINT,
Никакого закомментированного кода быть не должно.

2023-01-09 19:46 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explorewithme/main/model/Event.java
> +//    @Column(name = "views")
В коде не должно быть закомментированных строчек кода

2023-01-09 19:46 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explorewithme/main/model/EventSort.java
> +public enum EventSort {
Этот класс где-то используется?

2023-01-09 19:46 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/explorewithme/main/service/impl/CategoryServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size, Sort.by("name").ascending());
Параметры пагинации не валидируются ни аннотациями в контроллере, ни вручную здесь.

2023-01-09 19:46 UTC, sergeymamonov commented on stats-service/pom.xml
> +<!--    <properties>-->
В коде не должно быть закомментированных строчек кода

2023-01-09 19:46 UTC, sergeymamonov commented on stats-service/src/main/resources/schema.sql
> +    timestamp_ TIMESTAMP WITHOUT TIME ZONE NOT NULL,
В нижнем подчеркивании у названия колонки timestamp_ есть смысл?

2023-01-10 06:06 UTC, bad-decision commented
Замечания исправлены. Валидация добавлена на уровне контроллера.

2023-01-10 08:53 UTC, sergeymamonov approved these changes

2023-01-10 18:01 UTC, merged